"""
HTML reporter — self-contained report with embedded CSS and severity color coding.
"""

from __future__ import annotations

import html as html_module
from datetime import datetime
from typing import List

from risk_scanner.core.models import Finding, ScanResult, Severity
from risk_scanner.reporters import BaseReporter

_SEV_COLOR = {
    "CRITICAL": "#c0392b",
    "HIGH": "#e67e22",
    "MEDIUM": "#f1c40f",
    "LOW": "#3498db",
    "INFO": "#95a5a6",
}

_CSS = """
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         margin: 0; padding: 24px; background: #f5f5f5; color: #333; }
  h1, h2, h3 { margin-top: 0; }
  .header { background: #1a1a2e; color: #fff; padding: 24px; border-radius: 8px; margin-bottom: 24px; }
  .header h1 { color: #e0e0e0; }
  .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  .summary-table th { background: #2c3e50; color: #fff; padding: 10px 14px; text-align: left; }
  .summary-table td { padding: 10px 14px; border-bottom: 1px solid #ddd; background: #fff; }
  .badge { display: inline-block; padding: 3px 10px; border-radius: 12px;
           color: #fff; font-size: 12px; font-weight: bold; }
  .finding-card { background: #fff; border-left: 5px solid #ccc;
                  padding: 16px; margin-bottom: 16px; border-radius: 4px;
                  box-shadow: 0 1px 3px rgba(0,0,0,.1); }
  .finding-card pre { background: #f8f8f8; padding: 8px; border-radius: 4px;
                      overflow-x: auto; font-size: 12px; }
  .technique-tag { display: inline-block; background: #2980b9; color: #fff;
                   padding: 2px 8px; border-radius: 4px; font-size: 12px; margin: 2px; }
  .control-tag { display: inline-block; background: #27ae60; color: #fff;
                 padding: 2px 8px; border-radius: 4px; font-size: 12px; margin: 2px; }
  .footer { text-align: center; color: #999; margin-top: 32px; font-size: 12px; }
</style>
"""


class HTMLReporter(BaseReporter):
    def render(self, result: ScanResult) -> str:
        ts = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
        body_parts: List[str] = [
            "<!DOCTYPE html><html lang='en'><head>",
            f"<meta charset='UTF-8'><title>Risk Scanner — {result.scan_id}</title>",
            _CSS,
            "</head><body>",
            f"<div class='header'><h1>Risk Scanner Report</h1>",
            f"<p>Scan ID: <strong>{result.scan_id}</strong> &nbsp;|&nbsp; ",
            f"Artifact: <code>{html_module.escape(result.artifact_path)}</code><br>",
            f"Generated: {ts} &nbsp;|&nbsp; Duration: {result.duration_ms}ms</p></div>",
        ]

        # Severity summary
        body_parts.append("<h2>Severity Summary</h2>")
        body_parts.append("<table class='summary-table'><tr>"
                          "<th>Severity</th><th>Count</th></tr>")
        for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
            count = sum(1 for f in result.findings if f.severity == sev)
            if count:
                color = _SEV_COLOR[sev.value]
                body_parts.append(
                    f"<tr><td><span class='badge' style='background:{color}'>"
                    f"{sev.value}</span></td><td>{count}</td></tr>"
                )
        body_parts.append("</table>")

        # Findings
        body_parts.append(f"<h2>Findings ({len(result.findings)})</h2>")
        for finding in result.findings:
            body_parts.extend(self._render_finding(finding))

        # Footer
        body_parts.append(
            "<div class='footer'>Generated by risk-scanner 0.1.0 · "
            "Ask Claude to explain any finding or generate a remediation ticket.</div>"
            "</body></html>"
        )
        return "\n".join(body_parts)

    def _render_finding(self, finding: Finding) -> List[str]:
        ev = finding.evidence
        color = _SEV_COLOR.get(finding.severity.value, "#ccc")
        parts = [
            f"<div class='finding-card' style='border-left-color:{color}'>",
            f"<h3><span class='badge' style='background:{color}'>{finding.severity.value}</span> "
            f"&nbsp;<code>{html_module.escape(finding.id)}</code> — "
            f"<strong>{html_module.escape(finding.taxonomy_code)}</strong> "
            f"<small>({finding.domain.value})</small></h3>",
        ]
        if ev.file_path:
            loc = html_module.escape(ev.file_path)
            line = f" L{ev.line_start}" if ev.line_start else ""
            parts.append(f"<p><strong>Location:</strong> <code>{loc}{line}</code></p>")
        parts.append(f"<p>{html_module.escape(finding.severity_rationale)}</p>")
        if finding.summary:
            parts.append(f"<p><em>{html_module.escape(finding.summary)}</em></p>")
        if finding.attack_chain:
            parts.append("<p><strong>ATT&amp;CK Techniques:</strong><br>")
            for atk in finding.attack_chain:
                parts.append(
                    f"<span class='technique-tag'>{html_module.escape(atk.technique_id)}</span>"
                )
            parts.append("</p>")
        if finding.control_gaps:
            parts.append("<p><strong>Control Gaps:</strong><br>")
            for ctrl in finding.control_gaps[:5]:
                label = f"{ctrl.control_id} ({ctrl.framework})"
                parts.append(f"<span class='control-tag'>{html_module.escape(label)}</span>")
            parts.append("</p>")
        if finding.remediation:
            parts.append(f"<p><strong>Remediation:</strong> {html_module.escape(finding.remediation)}</p>")
        if ev.snippet:
            parts.append(f"<pre>{html_module.escape(ev.snippet[:300])}</pre>")
        parts.append("</div>")
        return parts
