"""
CLI generate-policy command — export a scan policy preset as YAML.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import typer
from rich.console import Console

app = typer.Typer()
console = Console()

_PRESETS = {
    "strict": {
        "enabled_domains": ["cve", "cwe", "attack", "policy", "framework"],
        "enabled_frameworks": ["soc2", "nist-800-53",  "iso27001"],
        "severity_threshold": "LOW",
        "enrichment_enabled": True,
        "meta_analysis_enabled": True,
        "enrichment_min_severity": "LOW",
    },
    "cve-only": {
        "enabled_domains": ["cve"],
        "enabled_frameworks": ["nist-800-53", "soc2","iso27001"],
        "severity_threshold": "MEDIUM",
        "enrichment_enabled": True,
        "meta_analysis_enabled": True,
        "enrichment_min_severity": "MEDIUM",
    },
    "iac": {
        "enabled_domains": ["policy", "cve"],
        "enabled_frameworks": ["nist-800-53", "soc2","iso27001"],
        "severity_threshold": "MEDIUM",
        "enrichment_enabled": True,
        "meta_analysis_enabled": True,
        "enrichment_min_severity": "MEDIUM",
    },
    "cicd": {
        "enabled_domains": ["cve", "cwe", "policy"],
        "enabled_frameworks": ["nist-800-53", "soc2","iso27001"],
        "severity_threshold": "HIGH",
        "enrichment_enabled": False,
        "meta_analysis_enabled": True,
        "enrichment_min_severity": "HIGH",
        "max_findings_per_domain": 50,
    },
    "soc2": {
        "enabled_domains": ["cve", "policy", "framework"],
        "enabled_frameworks": ["soc2"],
        "severity_threshold": "MEDIUM",
        "enrichment_enabled": True,
        "meta_analysis_enabled": True,
        "enrichment_min_severity": "MEDIUM",
    },
}


@app.command("generate-policy")
def cmd_generate_policy(
    preset: str = typer.Option(
        "strict",
        "--preset", "-p",
        help=f"Policy preset: {', '.join(_PRESETS.keys())}",
    ),
    output: Optional[Path] = typer.Option(
        None, "--output", "-o",
        help="Output YAML file path (default: stdout)",
    ),
) -> None:
    """Export a scan policy preset as a YAML file."""
    import yaml

    if preset not in _PRESETS:
        console.print(f"[red]Unknown preset: {preset!r}. Choose from: {', '.join(_PRESETS.keys())}[/red]")
        raise typer.Exit(1)

    policy_data = _PRESETS[preset]
    yaml_str = yaml.dump(policy_data, default_flow_style=False, sort_keys=False)

    header = (
        f"# risk-scanner policy — preset: {preset}\n"
        f"# Generated by: risk-scanner generate-policy --preset {preset}\n"
        f"# Load with: risk-scanner scan <path> --policy <this-file>\n\n"
    )

    if output:
        output.write_text(header + yaml_str)
        console.print(f"[green]Policy written to {output}[/green]")
    else:
        print(header + yaml_str)
